mac: fix broken harden runtime
According to stackoverflow, Using TRUE for XCODE_ATTRIBUTE_ENABLE_HARDENED_RUNTIME
will in fact generate NO in xcode project.
The correct value to set for the attribute is YES (again, at least in xcode 11).

Fixed a bug that entitlements would be overrided when doing codesign.

Tested with "lldb -p $(pgrep seafile-applet)" (for hardened runtime,
debugger should not attach to its process and get denied error like
below)
```
(lldb) process attach --pid 89428
error: attach failed: attach failed (Not allowed to attach to process.  Look in the console messages (Console.app), near the debugserver entries, when the attach failed.  The subsystem that denied the attach permission will likely have logged an informative message about why it was denied.)
```

Due to the limited debugging when built with harden runtime, it is
better to build with it only when it comes to release build.

harden runtime was introduced by commit 0537a769271035d2df02bd27d0dff2ecc4cd36fc

command `codesign -d --entitlements :- seafile-applet.app` should print something like:
```
Executable=/Users/ko/seafile-client/seafile-applet.app/Contents/MacOS/seafile-applet
Warning: Specifying ':' in the path is deprecated and will not work in a future release
```

Reference: https://stackoverflow.com/questions/56023947/cmake-xcode-generator-add-capability-hardened-runtime/56026083
and https://developer.apple.com/documentation/security/hardened_runtime?language=objc
and https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/resolving_common_notarization_issues?language=objc